### ISSUE TITLE
generate_mesh_dataset.py

### ISSUE THREAD

**Issue by MacBook-Pro-gala** [yinguobing/facial-landmark-detection-hrnet#6]
after I use generate_mesh_dataset.py,A 300vw.record file was generated.But how should I use this file for model training.
```
Traceback (most recent call last):
  File "train.py", line 167, in <module>
    model.fit(dataset_train,
  File "/Users/liuyuhan/miniforge3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1110, in fit
    raise ValueError('Expect x to be a non-empty array or dataset.')
ValueError: Expect x to be a non-empty array or dataset.
```

**Comment by yinguobing** [comment]
正如错误信息所述，`x`必须是非空矩阵。建议把当前`x`的具体数值打印出来看下。

**Comment by shojint** [comment]
The model does not read record file. Instead it reads a directory with images and json files. Is that correct?
